config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", include("dashboard.urls")),
    path("project/", include("project.urls")),
    path("ifx/", include("productMarketing.urls")),
    path("ifx/", include("productMarketingDwh.urls")),
    path("ifx/", include("snapshots.urls")),
    path("ifx/", include("analytics.urls")),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("core.users.urls")),
    path("accounts/", include("allauth.urls")),
    path("chaining/", include("smart_selects.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

core/analytics/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('productMarketing/businessInsights',
         views.businessInsights, name='analytics'),
    path('productMarketing/dataSources/pmd',
         views.productMasterData, name='productMasterData'),
    path('productMarketing/dataSources/vrfc', views.vrfc, name='vrfc'),
    path('productMarketing/dataSources/dragon', views.dragon, name='dragon'),
    path('productMarketing/dataSources/pmdFullList',
         views.pmdFullList, name='productFullList'),
    path('productMarketing/dataSources/pmdFullListSalesNames',
         views.pmdFullListSalesNames, name='pmdFullListSalesNames'),

]

core/project/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path(
        "create/",
        views.CreateProjectView.as_view(),
        name="create_project_view",
    ),

    path(
        "editDraft/",
        views.EditProjectDraftView.as_view(),
        name="edit_project_draft_view",
    ),

    path('editDraft/<int:projectId>', views.EditProjectDraftEntry,
         name='edit_project_draft_entry'),

    path('volumeTypeSelect/',
         views.SelectVolumeEntryType, name='create_volume_view'),
    path(
        "volumeAutomatic/",
        views.CreateVolumeAutomaticView.as_view(),
        name="create_volume_automatic_view",
    ),
    path(
        "volumeExcel/",
        views.CreateVolumeExcelView.as_view(),
        name="create_volume_excel_view",
    ),
    path(
        "volumeExcelMonth/",
        views.CreateVolumeExcelMonthView.as_view(),
        name="create_volume_excel_month_view",
    ),
    path(
        "pricing/",
        views.CreatePricingView.as_view(),
        name="create_pricing_view",
    ),
    path("series-lists/", views.series_list_json, name="series_list_json"),
    path("package-lists/", views.package_list_json, name="package_list_json"),
    path("sales-names-lists/", views.sales_name_json,
         name="sales_name_list_json"),

]

core/users/urls.py
from django.urls import path

from core.users import views


urlpatterns = [
    path("redirect/", view=views.UserRedirectView.as_view(), name="user_redirect_view"),
    path("update/", view=views.UserUpdateView.as_view(), name="user_update_view"),
    path(
        "<str:username>/", view=views.UserDetailView.as_view(), name="user_detail_view"
    ),
]

core/project/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import MaxValueValidator, MinValueValidator
from smart_selects.db_fields import ChainedForeignKey
from django.db.models import UniqueConstraint
# Create your models here.

# getting used user model
User = get_user_model()


class ApplicationLine(models.Model):
    applicationLineShortName = models.CharField(max_length=10)
    applicationLineLongName = models.CharField(max_length=20)


class LegalEntities(models.Model):
    leShortName = models.CharField(max_length=5)
    leLongName = models.CharField(max_length=35)


class marketerMetadata(models.Model):

    name = models.CharField(max_length=40, blank=True, null=True)
    familyName = models.CharField(max_length=40, blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=1)
    country = models.CharField(max_length=15, blank=True, null=True)
    legalEntity = models.ForeignKey(
        LegalEntities, on_delete=models.PROTECT, blank=True, null=True
    )
    applicationLine = models.ForeignKey(
        ApplicationLine, on_delete=models.PROTECT, blank=True, null=True
    )  # default = "ATV.PSE"

    def __str__(self):
        return f"{self.name} {self.familyName}"


class ApplicationMain(models.Model):
    appMainDescription = models.CharField(max_length=40, blank=True, null=True)

    def __str__(self):
        return self.appMainDescription


class ApplicationDetail(models.Model):

    appDetailDescription = models.CharField(
        max_length=40, blank=True, null=True)
    appMain = models.ForeignKey(
        ApplicationMain, on_delete=models.PROTECT, blank=True, null=True
    )

    def __str__(self):
        return self.appDetailDescription


class MainCustomers(models.Model):
    customerName = models.CharField(max_length=40, blank=True, null=True)
    valid = models.BooleanField(default=False, blank=True, null=True)

    def __str__(self):
        return self.customerName


class FinalCustomers(models.Model):
    # relation removed upon agreement with customer on nov 25th
    """
    mainCust = models.ForeignKey(
        MainCustomers, on_delete=models.SET_NULL, null=True
    )
    """
    finalCustomerName = models.CharField(max_length=40, blank=True, null=True)
    valid = models.BooleanField(default=False, blank=True, null=True)

    def __str__(self):
        return self.finalCustomerName
    """
    class Meta:
        unique_together = ["mainCust", "finalCustomerName"]
    """


class ProductFamily(models.Model):
    family_name = models.CharField(max_length=200)
    valid = models.BooleanField(default=False, blank=True, null=True)

    def __str__(self):
        return self.family_name


class ProductSeries(models.Model):
    family = models.ForeignKey(ProductFamily, on_delete=models.CASCADE)
    series = models.CharField(max_length=200)
    description = models.CharField(max_length=40, blank=True, null=True)
    valid = models.BooleanField(default=False, blank=True, null=True)

    def __str__(self):
        return self.series


class ProductPackage(models.Model):
    series = models.ForeignKey(ProductSeries, on_delete=models.CASCADE)
    package = models.CharField(max_length=200)
    description = models.CharField(max_length=40, blank=True, null=True)
    valid = models.BooleanField(default=False, blank=True, null=True)

    def __str__(self):
        return self.package


class Product(models.Model):
    hfg = models.CharField(max_length=20, blank=True, null=True)
    ppos = models.CharField(max_length=30, blank=True, null=True)
    rfp = models.CharField(max_length=40, blank=True, null=True)
    package = models.ForeignKey(
        ProductPackage, on_delete=models.SET_NULL, null=True)
    basicType = models.CharField(max_length=40, blank=True, null=True)
    availablePGS = models.CharField(max_length=40, blank=True, null=True)
    valid = models.BooleanField(default=False, blank=True, null=True)

    def __str__(self):
        return f"{self.rfp}"


class SalesName(models.Model):
    rfp = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=40)
    dummy = models.BooleanField(default=False, blank=True, null=True)

    def __str__(self):
        return self.name


class Distributors(models.Model):
    distributorName = models.CharField(max_length=40, blank=True, null=True)

    def __str__(self):
        return self.distributorName


class EMS(models.Model):
    emsName = models.CharField(max_length=40, blank=True, null=True)

    def __str__(self):
        return self.emsName


class Tier1(models.Model):
    tierOneName = models.CharField(max_length=40, blank=True, null=True)

    def __str__(self):
        return self.tierOneName


class OEM(models.Model):
    oemName = models.CharField(max_length=40, blank=True, null=True)

    def __str__(self):
        return self.oemName


class SalesContacts(models.Model):

    name = models.CharField(max_length=40, blank=True, null=True)
    deptarment = models.CharField(max_length=40, blank=True, null=True)

    def __str__(self):
        return self.name


class Project(models.Model):

    ALLOWABLE_TYPES_PROJECT_STATUS = (
        ("100", "BW (100%)"),
        ("90", "DW (90%)"),
        ("60", "DI (60%)"),
        ("40", "DI (40%)"),
        ("10", "OP (10%)"),
        ("0", "LO (0%)"),
    )

    ALLOWABLE_TYPES_REGION = (
        ("EMEA", "EMEA"),
        ("AMERICAS", "AMERICAS"),
        ("AP", "AP"),
        ("JAPAN", "JAPAN"),
        ("GC", "GC"),
        ("DIVERSE", "DIVERSE"),
    )

    ALLOWABLE_TYPES_DCCHANNEL = (
        ("direct", "Direct"),
        ("distribution", "Distribution"),
    )

    ALLOWABLE_TYPES_PRICE_STATUS = (
        ("estim", "Estimation"),
        ("quote", "Quotation"),
        ("contr", "Contract"),
    )

    productMarketer = models.ForeignKey(
        marketerMetadata, on_delete=models.PROTECT, verbose_name="Product Marketer"
    )
    spNumber = models.IntegerField(blank=True, null=True)

    applicationMain = models.ForeignKey(
        ApplicationMain, on_delete=models.PROTECT, verbose_name="Application Main"
    )

    applicationDetail = ChainedForeignKey(
        ApplicationDetail,
        chained_field="applicationMain",
        chained_model_field="appMain",
        show_all=False,
        auto_choose=True,
        sort=True,
        on_delete=models.CASCADE,
        null=True,
        verbose_name="Application Detail",
    )

    familyPriceApplicable = models.BooleanField(
        default=False, blank=True, null=True)
    familyPriceDetails = models.CharField(max_length=50, blank=True, null=True)
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, blank=True, null=True)
    modifiedDate = models.DateTimeField(auto_now=True)
    creationDate = models.DateTimeField(auto_now_add=True)

    estimatedSop = models.IntegerField(
        blank=True,
        null=True,
        default=2020,
        validators=[MinValueValidator(2020), MaxValueValidator(2050)],
        verbose_name="Estimated SOP",
    )
    status = models.CharField(
        max_length=15, choices=ALLOWABLE_TYPES_PROJECT_STATUS, default=0
    )
    region = models.CharField(
        max_length=10, choices=ALLOWABLE_TYPES_REGION, default="EMEA"
    )
    secondRegion = models.CharField(
        max_length=10,
        choices=ALLOWABLE_TYPES_REGION,
        blank=True,
        null=True,
        verbose_name="Second Region",
    )

    dcChannel = models.CharField(
        max_length=12, choices=ALLOWABLE_TYPES_DCCHANNEL, blank=True, null=True
    )
    valid = models.BooleanField(default=True, blank=True, null=True)
    mainCustomer = models.ForeignKey(
        MainCustomers,
        on_delete=models.PROTECT,
        blank=False,
        null=True,
        verbose_name="Main Customer",
    )

    finalCustomer = models.ForeignKey(
        FinalCustomers,
        on_delete=models.PROTECT,
        blank=False,
        null=True,
        verbose_name="Final Customer",
    )

    # chained foreign key removed after customer alignment
    """
    finalCustomer = ChainedForeignKey(
        FinalCustomers,
        chained_field="mainCustomer",
        chained_model_field="mainCust",
        verbose_name="Final Customer",
        show_all=False,
        auto_choose=True,
        sort=True,
        null=True,
    )
    """
    # salesName = models.ForeignKey(
    #     SalesName, on_delete=models.PROTECT, blank=True, null=True
    # )

    """
    product_family = models.ForeignKey(
        ProductFamily, on_delete=models.SET_NULL, null=True
    )
    product_series = ChainedForeignKey(
        ProductSeries,
        chained_field="product_family",
        chained_model_field="family",
        show_all=False,
        auto_choose=True,
        sort=True,
        null=True,
    )
    product_package = ChainedForeignKey(
        ProductPackage,
        chained_field="product_series",
        chained_model_field="series",
        show_all=False,
        auto_choose=True,
        sort=True,
        null=True,
    )

    product = ChainedForeignKey(
        Product,
        chained_field="product_package",
        chained_model_field="package",
        show_all=False,
        auto_choose=False,
        sort=True,
        null=True,
    )
    """
    sales_name = models.ForeignKey(
        SalesName,
        on_delete=models.SET_NULL,
        null=True,
    )

    comment = models.TextField(blank=True, null=True)
    projectName = models.CharField(max_length=150, verbose_name="Project Name")
    projectDescription = models.CharField(
        max_length=400, default="", blank=True, null=True
    )
    draft = models.BooleanField(default=True, blank=True, null=True)
    priceValidUntil = models.DateField(blank=True, null=True)
    priceType = models.CharField(
        max_length=5, choices=ALLOWABLE_TYPES_PRICE_STATUS, blank=True, null=True
    )

core/snapshots/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator

# from betterforms.multiform import MultiForm, MultiModelForm

from .models import SnapshotMetaData


class CreateSnapshotForm(forms.ModelForm):

    class Meta:
        model = SnapshotMetaData
        fields = (
            # first tab fields
            "user",
            "snapshotName",
            "tag",
            "fileName"
        )

core/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

core/dashboard/views.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.


class Dashboard(LoginRequiredMixin, View):
    template_name = "dashboard/dashboard.html"

    def get(self, request, *args, **kwargs):
        # add data here to render to the template
        context = {"heading": "Dashboard", "pageview": "Dashboard"}
        return render(request, self.template_name, context)

core/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ("first_name", "last_name")
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("dashboard_view")

core/templates/project/project_create_view/done.html
{% extends 'base.html' %} {% load custom_tags static crispy_forms_tags %} {% block extra_css %}
<link rel="stylesheet" href="{% static 'libs/spreadsheet/dist/css/jquery.jexcel.css' %}" />
<link rel="stylesheet" href="{% static 'libs/spreadsheet/dist/css/jquery.jcalendar.css' %}" />

{% endblock extra_css %} {% block title %} Success {% endblock title %} {% block contents %}

<div class="card-body">
    <h5 class="h3">Project Entry</h5>
    <p class="card-title-desc">Project entry got completed!</p>
    <div class="row justify-content-center">
        <div class="fluid-container" style="z-index: 1">
            <ul class="progressbar p-0">
                <li class="active">Project Creation</li>
                <li class="active">Volume Entry</li>
                <li class="active">Pricing Entry</li>
                <li class="active">Done</li>
            </ul>
        </div>
    </div>
    <div class="row justify-content-center align-items-center vh-75">
        <div class="col-12">
            <div class="text-center">
                <h3 class="h1">Well done!</h3>
                <div class="mb-4">
                    <i class="mdi mdi-check-circle-outline text-success display-4"></i>
                </div>
                <div>
                    <h5>Form Submitted</h5>
                    <p class="text-muted">You form was submitted successfully!</p>
                </div>
            </div>
        </div>
        <div class="d-flex flex-wrap justify-content-end gap-2">
            <a href="{% url 'dashboard_view' %}" class="btn btn-secondary">Go to Dashboard</a>
            <a href="{% url 'create_project_view' %}" class="btn btn-success">Add another project</a>
        </div>
    </div>
</div>

{% endblock contents %}

core/templates/project/project_create_view/step1.html
{% extends 'base.html' %} {% load custom_tags static crispy_forms_tags %} {% block extra_css %}
<link href="{% static 'libs/select2/dist/css/select2.min.css'%}" rel="stylesheet" type="text/css" />
{% endblock extra_css %} {% block title %} Project Creation {% endblock title %} {% block contents %}

<div class="card-body">
    <h5 class="h3">Project Entry</h5>
    <p class="card-title-desc">Required fields are marked with *</p>
    <div class="row justify-content-center">
        <div class="fluid-container" style="z-index: 1">
            <ul class="progressbar p-0">
                <li class="active">Project Creation</li>
                <li>Volume Entry</li>
                <li>Pricing Entry</li>
                <li>Done</li>
            </ul>
        </div>

        <div class="col-12">
            <form method="post">
                {% csrf_token %}
                <div class="mt-4">
                    {{ form.media.js }}
                    <div class="row">
                        {% if form.non_field_errors %} {% for error in form.non_field_errors %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{error}}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                        {% endfor %} {% endif %}
                        <div class="col-12 mb-3">
                            <div class="mt-4">
                                <div class="accordion" id="createProject">
                                    <div class="accordion-item">
                                        <h2 class="accordion-header" id="headingOne">
                                            <button class="accordion-button fw-medium" type="button" data-bs-toggle="collapse" data-bs-target="#keyFacts" aria-expanded="true" aria-controls="keyFacts">Key Facts</button>
                                        </h2>
                                        <div id="keyFacts" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#createProject">
                                            <div class="accordion-body">
                                                <div class="row">
                                                    <div class="col-md-4 col-lg-3">{{form.projectName|as_crispy_field}}</div>
                                                    <div class="col-md-4 col-lg-3">{{form.productMarketer|as_crispy_field}}</div>
                                                    <div class="col-md-4 col-lg-3">{{form.region|as_crispy_field}}</div>
                                                    <div class="col-md-4 col-lg-3">{{form.secondRegion|as_crispy_field}}</div>
                                                    <div class="col-md-4 col-lg-3">{{form.estimatedSop|as_crispy_field}}</div>
                                                    <div class="col-md-4 col-lg-3">{{form.status|as_crispy_field}}</div>
                                                    <div class="col-md-4 col-lg-3">{{form.salesContact|as_crispy_field}}</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="accordion-item">
                                        <h2 class="accordion-header" id="headingTwo">
                                            <button class="accordion-button fw-medium collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#customerInformation" aria-expanded="false" aria-controls="customerInformation">Customer Information</button>
                                        </h2>
                                        <div id="customerInformation" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#createProject">
                                            <div class="accordion-body">
                                                <div class="row">
                                                    <div class="col-md-4 col-lg-3">{{form.mainCustomer|as_crispy_field}}</div>
                                                    <div class="col-md-4 col-lg-3">{{form.finalCustomer|as_crispy_field}}</div>

                                                    <div class="col-md-4 col-lg-3">{{form.distributor|as_crispy_field}}</div>
                                                    <div class="col-md-4 col-lg-3">{{form.ems|as_crispy_field}}</div>

                                                    <div class="col-md-4 col-lg-3">{{form.tier1|as_crispy_field}}</div>
                                                    <div class="col-md-4 col-lg-3">{{form.oem|as_crispy_field}}</div>
                                                    <div class="col-md-4 col-lg-3">{{form.vpaCustomer|as_crispy_field}}</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="accordion-item">
                                        <h2 class="accordion-header" id="headingThree">
                                            <button class="accordion-button fw-medium collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#productInformation" aria-expanded="false" aria-controls="productInformation">Product Information</button>
                                        </h2>
                                        <div id="productInformation" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#createProject">
                                            <div class="accordion-body">
                                                <div class="row">
                                                    <div class="col-md-4 col-lg-3">{{form.product_family|as_crispy_field}}</div>
                                                    <div class="col-md-4 col-lg-3">{{form.product_series|as_crispy_field}}</div>
                                                    <div class="col-md-4 col-lg-3">{{form.product_package|as_crispy_field}}</div>
                                                    <div class="col-md-4 col-lg-3">{{form.sales_name|as_crispy_field}}</div>
                                                    <div class="col-md-4 col-lg-3">{{form.applicationMain|as_crispy_field}}</div>
                                                    <div class="col-md-4 col-lg-3">{{form.applicationDetail|as_crispy_field}}</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- end accordion -->
                            </div>
                        </div>

                        <div class="mb-3">{{form.comment|as_crispy_field}}</div>

                        <div class="d-flex flex-wrap justify-content-end gap-2">
                            <input type="submit" class="btn btn-success" value="Next Step" />
                        </div>
                    </div>

                    <!-- end accordion -->
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock contents %} {% block extra_javascript %}
<script src="{% static 'libs/select2/dist/js/select2.min.js'%}"></script>
<script>
    $(document).ready(function () {
        // select2 on sales name

        var product_family = $("#id_product_family")
        var product_series = $("#id_product_series")
        var product_package = $("#id_product_package")
        var sales_name = $("#id_sales_name")

        product_family.select2({
            width: "100%",
        })
        product_series.select2({
            width: "100%",
        })
        product_package.select2({
            width: "100%",
        })
        sales_name.select2({
            width: "100%",
        })

        // select series
        product_family.on("select2:select", function () {
            $.post("{% url 'series_list_json' %}", {query: this.value}, function (data, status) {
                var series = data.data
                product_series.empty().trigger("change")
                var newOptions = [new Option("---------", "", true, true)]
                series.forEach((element, key) => {
                    newOptions.push(new Option(element.text, element.id, false, false))
                })
                product_series.append(newOptions).trigger("change")
            })
        })
        // select packages
        product_series.on("select2:select", function () {
            $.post("{% url 'package_list_json' %}", {query: this.value}, function (data, status) {
                var packages = data.data
                product_package.empty().trigger("change")
                var newOptions = [new Option("---------", "", true, true)]
                packages.forEach((element, key) => {
                    newOptions.push(new Option(element.text, element.text, false, false))
                })
                product_package.append(newOptions).trigger("change")
            })
        })
        // select sales name
        product_package.on("select2:select", function () {
            $.post("{% url 'sales_name_list_json' %}", {query: this.value}, function (data, status) {
                var names = data.data
                sales_name.empty().trigger("change")
                var newOptions = [new Option("---------", "", true, true)]
                names.forEach((element, key) => {
                    newOptions.push(new Option(element.text, element.text, false, false))
                })
                sales_name.append(newOptions).trigger("change")
            })
        })
    })
</script>

{% endblock extra_javascript %}

core/templates/project/project_create_view/step2a.html
{% extends 'base.html' %} {% load custom_tags static crispy_forms_tags %} {% block extra_css %}
{% endblock extra_css %} {% block title %} Volume Entry {% endblock title %} {% block contents %}

<div class="card-body">
    <h5 class="h3">Project Entry</h5>
    <p class="card-title-desc">Required fields are marked with *</p>
    <div class="row justify-content-center">
        <div class="fluid-container" style="z-index: 1">
            <ul class="progressbar p-0">
                <li class="active">Project Creation</li>
                <li class="active">Volume Entry</li>
                <li>Pricing Entry</li>
                <li>Done</li>
            </ul>
        </div>

        <div class="col-12 d-flex justify-content-center align-items-center h-30" id="choiceModel">
            <div class="d-flex flex-wrap gap-2">
                <button type="button" id="manual" class="btn btn-primary bg-brown btn-lg waves-effect waves-light" onclick="window.location.href='{% url 'create_volume_excel_view' %}';"  href="{% url 'create_volume_excel_view' %}" value="Excel" >Excel Copy & Paste</button>
                <button type="button" id="automatic" class="btn btn-secondary bg-magenta btn-lg waves-effect waves-light" onclick="window.location.href='{% url 'create_volume_automatic_view' %}';" href="{% url 'create_volume_automatic_view' %}" value="Automatic" >Automatic Volume Distribution</button>
            </div>
        </div>
    </div>
</div>

{% endblock contents %} 
{% block extra_javascript %}
{% endblock extra_javascript %}